version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: |
            apt-get update && apt-get install -y gcc g++ 
            apt-get update && apt-get -y install make
      - run:
          name: Install CMAKE
          command: |
            apt-get update && apt-get install -y wget
            CMAKE_VERSION=3.19.0
            CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.*}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
            wget ${CMAKE_URL}
            tar -xvzf cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
            chmod +x ./cmake-${CMAKE_VERSION}-Linux-x86_64/bin/ccmake
            chmod +x ./cmake-${CMAKE_VERSION}-Linux-x86_64/bin/cmake
            chmod +x ./cmake-${CMAKE_VERSION}-Linux-x86_64/bin/cpack
            chmod +x ./cmake-${CMAKE_VERSION}-Linux-x86_64/bin/ctest
            DIR=$(pwd)
            ln -s $DIR/cmake-${CMAKE_VERSION}-Linux-x86_64/bin/ccmake /usr/bin/ccmake
            ln -s $DIR/cmake-${CMAKE_VERSION}-Linux-x86_64/bin/cmake /usr/bin/cmake
            ln -s $DIR/cmake-${CMAKE_VERSION}-Linux-x86_64/bin/cpack /usr/bin/cpack
            ln -s $DIR/cmake-${CMAKE_VERSION}-Linux-x86_64/bin/ctest /usr/bin/ctest
            cmake --version
      - run:
          name: Build Project
          command: 'cd Software && cmake -B _build && cmake --build _build'